input:
  # This is way-simplified version of the meta-programming we'd need to
  # actually do. Similar to how PangeoForge's runner config takes a
  # dot-delimited module string, we need more information than this.
  # Also, everything here is made up.
  class: "beam.io.HTTPFile"
  kwargs:
    url: "https://example.com/something"
